name: Electron Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build Electron App
        run: npm run package

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: macos-app
          path: release/build/*.dmg
